### ISSUE TITLE
lemmy-universal-link-switcher userscript

### ISSUE THREAD

**Issue by cppxor2arr** [dbeley/awesome-lemmy#13]
This userscript can even rewrite Lemmy posts/comments to point to your home instance.

I've used it and it works well. It even works on Android (Firefox).

https://gitlab.com/azzurite/lemmy-universal-link-switcher
https://greasyfork.org/en/scripts/469273-lemmy-universal-link-switcher

**Comment by dbeley** [comment]
Thanks it's now in the list!
