### ISSUE TITLE
LemmyTools Userscript

### ISSUE THREAD

**Issue by JarnoB** [dbeley/awesome-lemmy#6]
Hi,

I just discovered this user script, which adds functionally to Lemmy. I think it's pretty awesome so far. Similar to what RES is to Reddit, although it obviously doesn't have as much functionality as RES right now because it's a fresh project. You might want to add it to the list.

https://github.com/howdy-tsc/LemmyTools

https://greasyfork.org/en/scripts/469169-lemmytools

**Comment by dbeley** [comment]
Thanks it's now part of the list :+1:
